// ========== 数据层 ==========
const ALBUM_COVERS = {
  echoes: "/spark/app/app_17c64618xwu/runtime/api/v1/storage/object/bucket_aadkqcoy2rkbg_static/static%2Faadkqb2eaf2gi_ve_miaoda",
  nocturnal: "/spark/app/app_17c64618xwu/runtime/api/v1/storage/object/bucket_aadkqcoy2rkbg_static/static%2Faadkqbyuqpejq_ve_miaoda",
  wildwood: "/spark/app/app_17c64618xwu/runtime/api/v1/storage/object/bucket_aadkqcoy2rkbg_static/static%2Faadkqb4ak2kdq_ve_miaoda",
  orbital: "/spark/app/app_17c64618xwu/runtime/api/v1/storage/object/bucket_aadkqcoy2rkbg_static/static%2Faadkqb25ckqdi_ve_miaoda",
  golden: "/spark/app/app_17c64618xwu/runtime/api/v1/storage/object/bucket_aadkqcoy2rkbg_static/static%2Faadkqb5scj6fg_ve_miaoda",
  paper: "/spark/app/app_17c64618xwu/runtime/api/v1/storage/object/bucket_aadkqcoy2rkbg_static/static%2Faadkqb6m6moco_ve_miaoda",
};

const ALBUMS = [
  {
    id: "echoes",
    title: "Echoes of Dust",
    artist: "Marlow Vale",
    cover: ALBUM_COVERS.echoes,
    genre: "Modern Jazz",
    year: 1974,
    label: "Blue Note",
    condition: "Mint-",
    catalog: "BN-LA259-G",
    duration: "42:18",
    format: "LP, 12\"",
    speed: "33 ⅓ RPM",
    description: "一张被时间尘封的爵士经典，Marlow Vale 最具实验性的作品。铜管的回声在灰尘中起舞，仿佛永远停在那个夏天的录音棚里。",
    tracks: [
      { num: 1, title: "Dust Motel", duration: "5:42", side: "A" },
      { num: 2, title: "Crimson Hours", duration: "6:18", side: "A" },
      { num: 3, title: "Paperweight", duration: "4:33", side: "A" },
      { num: 4, title: "Velvet Static", duration: "7:02", side: "B" },
      { num: 5, title: "Echoes of Dust", duration: "8:14", side: "B" },
      { num: 6, title: "Slowburn", duration: "5:27", side: "B" },
      { num: 7, title: "Fade to Amber", duration: "5:02", side: "B" },
    ],
    color: "#C86A3E",
    owned: true,
    favorite: true,
    plays: 247,
    lastPlayed: "3 天前",
  },
  {
    id: "nocturnal",
    title: "Nocturnal Currents",
    artist: "Aether Sound",
    cover: ALBUM_COVERS.nocturnal,
    genre: "Ambient / Electronic",
    year: 2019,
    label: "Erased Tapes",
    condition: "NM",
    catalog: "ERATP127",
    duration: "56:44",
    format: "2LP, 180g",
    speed: "33 ⅓ RPM",
    description: "深夜电子氛围的杰作，将城市的霓虹灯光转化为声波。黑胶版的底噪本身就是音乐的一部分。",
    tracks: [
      { num: 1, title: "Night Swim", duration: "7:22", side: "A" },
      { num: 2, title: "Currents I", duration: "8:14", side: "A" },
      { num: 3, title: "Glass Towers", duration: "6:48", side: "B" },
      { num: 4, title: "Submerged", duration: "9:33", side: "B" },
      { num: 5, title: "Currents II", duration: "7:56", side: "C" },
      { num: 6, title: "Low Tide", duration: "5:41", side: "C" },
      { num: 7, title: "First Light", duration: "11:10", side: "D" },
    ],
    color: "#1a4a5a",
    owned: true,
    favorite: false,
    plays: 89,
    lastPlayed: "上周",
  },
  {
    id: "wildwood",
    title: "Wildwood Sessions",
    artist: "Iris & the Thorns",
    cover: ALBUM_COVERS.wildwood,
    genre: "Folk / Indie",
    year: 2021,
    label: "Secretly Canadian",
    condition: "NM",
    catalog: "SC420",
    duration: "38:52",
    format: "LP, Forest Green Vinyl",
    speed: "33 ⅓ RPM",
    description: "在树林里的小木屋录制的民谣专辑，你甚至能在背景里听到雨落在屋顶的声音。限量彩胶版本。",
    tracks: [
      { num: 1, title: "Moss & Stone", duration: "4:12", side: "A" },
      { num: 2, title: "Wildwood", duration: "5:06", side: "A" },
      { num: 3, title: "Thornbird", duration: "3:48", side: "A" },
      { num: 4, title: "Pines", duration: "6:21", side: "A" },
      { num: 5, title: "October Song", duration: "4:33", side: "B" },
      { num: 6, title: "Lantern", duration: "5:17", side: "B" },
      { num: 7, title: "Homecoming", duration: "5:44", side: "B" },
      { num: 8, title: "Ashes to Earth", duration: "3:51", side: "B" },
    ],
    color: "#7a8a4a",
    owned: true,
    favorite: true,
    plays: 156,
    lastPlayed: "昨天",
  },
  {
    id: "orbital",
    title: "Orbital Drift",
    artist: "Voyager Collective",
    cover: ALBUM_COVERS.orbital,
    genre: "Progressive Rock",
    year: 1978,
    label: "Harvest",
    condition: "VG+",
    catalog: "SHSP 4093",
    duration: "48:26",
    format: "LP, Gatefold",
    speed: "33 ⅓ RPM",
    description: "七十年代前卫摇滚的遗珠，整张专辑讲述一个宇航员在轨道上漂流的故事。折叠封面内附完整科幻小说短篇。",
    tracks: [
      { num: 1, title: "Liftoff", duration: "4:28", side: "A" },
      { num: 2, title: "Weightless", duration: "6:44", side: "A" },
      { num: 3, title: "Dark Side of the Mind", duration: "8:12", side: "A" },
      { num: 4, title: "Orbital Drift (Suite)", duration: "14:33", side: "B" },
      { num: 5, title: "Re-entry", duration: "5:17", side: "B" },
      { num: 6, title: "Home", duration: "9:12", side: "B" },
    ],
    color: "#2a3458",
    owned: true,
    favorite: false,
    plays: 72,
    lastPlayed: "2 周前",
  },
  {
    id: "golden",
    title: "Golden Hour",
    artist: "Delia Ray",
    cover: ALBUM_COVERS.golden,
    genre: "Soul / R&B",
    year: 1976,
    label: "Stax",
    condition: "VG",
    catalog: "STS-5525",
    duration: "36:40",
    format: "LP",
    speed: "33 ⅓ RPM",
    description: "Delia Ray 唯一的独唱专辑，灵魂乐黄金时代的代表作。这张首版黑胶在收藏市场上越来越难寻。",
    tracks: [
      { num: 1, title: "Sunny Side Up", duration: "3:24", side: "A" },
      { num: 2, title: "Golden Hour", duration: "4:12", side: "A" },
      { num: 3, title: "Honey Bee", duration: "3:48", side: "A" },
      { num: 4, title: "Let It Be Known", duration: "4:01", side: "A" },
      { num: 5, title: "Midnight Train", duration: "3:56", side: "A" },
      { num: 6, title: "Since You've Been Gone", duration: "4:28", side: "B" },
      { num: 7, title: "Easy Come Easy Go", duration: "3:34", side: "B" },
      { num: 8, title: "One More Time", duration: "4:52", side: "B" },
      { num: 9, title: "Goodnight My Love", duration: "4:25", side: "B" },
    ],
    color: "#D4923A",
    owned: false,
    favorite: true,
    plays: 38,
    lastPlayed: "1 个月前",
  },
  {
    id: "paper",
    title: "Paper Moon",
    artist: "Luna Park",
    cover: ALBUM_COVERS.paper,
    genre: "Indie Pop / Dream Pop",
    year: 2023,
    label: "Sub Pop",
    condition: "Mint",
    catalog: "SP 1520",
    duration: "41:05",
    format: "LP, Pink Vinyl",
    speed: "33 ⅓ RPM",
    description: "2023 年最让人惊喜的梦幻流行处女作。像把月光折成纸船，漂在你耳边。粉色胶限量 1000 张。",
    tracks: [
      { num: 1, title: "Paper Moon", duration: "4:02", side: "A" },
      { num: 2, title: "Crush", duration: "3:28", side: "A" },
      { num: 3, title: "Daisychain", duration: "4:15", side: "A" },
      { num: 4, title: "Sleepover", duration: "5:10", side: "A" },
      { num: 5, title: "Sundae", duration: "3:44", side: "A" },
      { num: 6, title: "Daydream", duration: "4:22", side: "B" },
      { num: 7, title: "Cloud 9", duration: "3:56", side: "B" },
      { num: 8, title: "Peach", duration: "3:33", side: "B" },
      { num: 9, title: "Last Summer", duration: "5:12", side: "B" },
      { num: 10, title: "Goodbye, Hello", duration: "3:23", side: "B" },
    ],
    color: "#B4838A",
    owned: true,
    favorite: true,
    plays: 312,
    lastPlayed: "今天",
  },
];

const GENRES = [
  { name: "全部", count: 128, id: "all" },
  { name: "爵士", count: 42, id: "jazz" },
  { name: "摇滚", count: 31, id: "rock" },
  { name: "民谣", count: 18, id: "folk" },
  { name: "电子", count: 15, id: "electronic" },
  { name: "灵魂乐", count: 12, id: "soul" },
  { name: "古典", count: 8, id: "classical" },
  { name: "嘻哈", count: 2, id: "hiphop" },
];

const PLAYLISTS = [
  { name: "深夜漫走", count: 24, mood: "Ambient", cover: ALBUM_COVERS.nocturnal },
  { name: "周末早晨", count: 18, mood: "Folk", cover: ALBUM_COVERS.wildwood },
  { name: "雨天书房", count: 31, mood: "Jazz", cover: ALBUM_COVERS.echoes },
  { name: "复古派对", count: 42, mood: "Soul", cover: ALBUM_COVERS.golden },
];

const USER = {
  name: "Vincent Lin",
  handle: "@vinyl_vince",
  bio: "黑胶收藏家 · 248 张 · 自 2015 年起",
  stats: {
    collection: 248,
    artists: 187,
    labels: 64,
    genres: 12,
    totalPlays: 4382,
    totalMinutes: 18746,
  },
  joined: "2019 年 3 月",
};

// 导出到全局
Object.assign(window, { ALBUMS, GENRES, PLAYLISTS, USER, ALBUM_COVERS });
